"""
Models for the monitoring app.
"""
from django.db import models
from django.utils import timezone
import uuid


class Transaction(models.Model):
    """Model to represent a financial transaction."""
    
    TRANSACTION_TYPE_CHOICES = [
        ('TRANSFER', 'Transfer'),
        ('DEPOSIT', 'Deposit'),
        ('WITHDRAWAL', 'Withdrawal'),
        ('PAYMENT', 'Payment'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    transaction_id = models.CharField(max_length=255, unique=True, db_index=True)
    account_id = models.CharField(max_length=255, db_index=True)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    currency = models.CharField(max_length=3, default='USD')
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPE_CHOICES)
    timestamp = models.DateTimeField(db_index=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['account_id', 'timestamp']),
            models.Index(fields=['transaction_id']),
            models.Index(fields=['created_at']),
        ]
    
    def __str__(self):
        return f"Transaction {self.transaction_id} - {self.account_id}"


class Rule(models.Model):
    """Model to represent a monitoring rule."""
    
    RULE_TYPE_CHOICES = [
        ('LARGE_TRANSACTION', 'Large Transaction'),
        ('HIGH_FREQUENCY', 'High Transaction Frequency'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, unique=True, db_index=True)
    rule_type = models.CharField(max_length=50, choices=RULE_TYPE_CHOICES)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True, db_index=True)
    created_by = models.CharField(max_length=255, default='system')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # Configuration fields for different rule types
    amount_threshold = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    transaction_frequency_limit = models.IntegerField(default=5, null=True, blank=True)
    time_window_minutes = models.IntegerField(default=1440, null=True, blank=True)  # 24 hours
    
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['is_active', 'created_at']),
            models.Index(fields=['rule_type']),
        ]
    
    def __str__(self):
        return self.name


class RuleAuditLog(models.Model):
    """Model to track changes to monitoring rules (audit trail)."""
    
    ACTION_CHOICES = [
        ('CREATE', 'Created'),
        ('UPDATE', 'Updated'),
        ('ACTIVATE', 'Activated'),
        ('DEACTIVATE', 'Deactivated'),
        ('DELETE', 'Deleted'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    rule = models.ForeignKey(Rule, on_delete=models.CASCADE, related_name='audit_logs')
    action = models.CharField(max_length=20, choices=ACTION_CHOICES)
    performed_by = models.CharField(max_length=255, default='system')
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    changes = models.JSONField(default=dict, blank=True)
    description = models.TextField(blank=True)
    
    class Meta:
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['rule', 'timestamp']),
            models.Index(fields=['action', 'timestamp']),
            models.Index(fields=['performed_by', 'timestamp']),
        ]
    
    def __str__(self):
        return f"{self.rule.name} - {self.action} by {self.performed_by}"


class Alert(models.Model):
    """Model to represent an alert generated by a rule."""
    
    ALERT_STATUS_CHOICES = [
        ('ACTIVE', 'Active'),
        ('REVIEWED', 'Reviewed'),
        ('DISMISSED', 'Dismissed'),
        ('RESOLVED', 'Resolved'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    rule = models.ForeignKey(Rule, on_delete=models.CASCADE, related_name='alerts')
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, related_name='alerts')
    account_id = models.CharField(max_length=255, db_index=True)
    status = models.CharField(max_length=20, choices=ALERT_STATUS_CHOICES, default='ACTIVE', db_index=True)
    details = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['account_id', 'created_at']),
            models.Index(fields=['status', 'created_at']),
            models.Index(fields=['rule', 'created_at']),
        ]
    
    def __str__(self):
        return f"Alert {self.id} - {self.rule.name}"
