"""
Serializers for the monitoring app.

These serializers handle validation and serialization of Transaction, Rule, Alert, and RuleAuditLog models.
"""
from rest_framework import serializers
from .models import Transaction, Rule, Alert, RuleAuditLog


class TransactionSerializer(serializers.ModelSerializer):
    """
    Serializer for Transaction model.
    
    Handles validation and serialization of financial transaction data.
    """
    
    class Meta:
        model = Transaction
        fields = [
            'id',
            'transaction_id',
            'account_id',
            'amount',
            'currency',
            'transaction_type',
            'timestamp',
            'created_at',
            'updated_at',
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']
        extra_kwargs = {
            'transaction_id': {
                'help_text': 'Unique transaction identifier (e.g., TXN001)',
            },
            'account_id': {
                'help_text': 'Account identifier (e.g., ACC123)',
            },
            'amount': {
                'help_text': 'Transaction amount in specified currency',
            },
            'currency': {
                'help_text': 'ISO 4217 currency code (e.g., USD, EUR)',
            },
            'transaction_type': {
                'help_text': 'Type of transaction: TRANSFER, DEPOSIT, WITHDRAWAL, PAYMENT',
            },
            'timestamp': {
                'help_text': 'Transaction timestamp in ISO 8601 format',
            },
        }


class RuleSerializer(serializers.ModelSerializer):
    """
    Serializer for Rule model.
    
    Handles validation and serialization of monitoring rules.
    Supports LARGE_TRANSACTION and HIGH_FREQUENCY rule types.
    """
    
    class Meta:
        model = Rule
        fields = [
            'id',
            'name',
            'rule_type',
            'description',
            'is_active',
            'amount_threshold',
            'transaction_frequency_limit',
            'time_window_minutes',
            'created_at',
            'updated_at',
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']
        extra_kwargs = {
            'name': {
                'help_text': 'Unique name for the rule',
            },
            'rule_type': {
                'help_text': 'Rule type: LARGE_TRANSACTION or HIGH_FREQUENCY',
            },
            'description': {
                'help_text': 'Detailed description of the rule',
            },
            'is_active': {
                'help_text': 'Enable/disable the rule',
            },
            'amount_threshold': {
                'help_text': 'Amount threshold for LARGE_TRANSACTION rules (e.g., 10000)',
            },
            'transaction_frequency_limit': {
                'help_text': 'Maximum transaction count for HIGH_FREQUENCY rules (default: 5)',
            },
            'time_window_minutes': {
                'help_text': 'Time window in minutes for HIGH_FREQUENCY rules (default: 1440 = 24 hours)',
            },
        }


class AlertSerializer(serializers.ModelSerializer):
    """
    Serializer for Alert model.
    
    Handles validation and serialization of alerts generated by rules.
    Includes related rule and transaction information.
    """
    
    rule_name = serializers.CharField(source='rule.name', read_only=True)
    transaction_id = serializers.CharField(source='transaction.transaction_id', read_only=True)
    
    class Meta:
        model = Alert
        fields = [
            'id',
            'rule',
            'rule_name',
            'transaction',
            'transaction_id',
            'account_id',
            'status',
            'details',
            'created_at',
            'updated_at',
        ]
        read_only_fields = ['id', 'rule', 'transaction', 'created_at', 'updated_at']
        extra_kwargs = {
            'rule': {
                'help_text': 'UUID of the triggered rule',
            },
            'transaction': {
                'help_text': 'UUID of the transaction that triggered the alert',
            },
            'account_id': {
                'help_text': 'Account identifier associated with the alert',
            },
            'status': {
                'help_text': 'Alert status: ACTIVE, REVIEWED, DISMISSED, RESOLVED',
            },
            'details': {
                'help_text': 'Additional alert details (JSON object with rule-specific information)',
            },
        }


class RuleAuditLogSerializer(serializers.ModelSerializer):
    """
    Serializer for RuleAuditLog model.
    
    Handles serialization of audit trail entries for rule changes.
    Tracks who made changes, when, and what was changed.
    """
    
    rule_name = serializers.CharField(source='rule.name', read_only=True)
    
    class Meta:
        model = RuleAuditLog
        fields = [
            'id',
            'rule',
            'rule_name',
            'action',
            'performed_by',
            'timestamp',
            'changes',
            'description',
        ]
        read_only_fields = ['id', 'rule', 'action', 'performed_by', 'timestamp', 'changes', 'description']
        extra_kwargs = {
            'rule': {
                'help_text': 'UUID of the rule',
            },
            'action': {
                'help_text': 'Type of action: CREATE, UPDATE, ACTIVATE, DEACTIVATE, DELETE',
            },
            'performed_by': {
                'help_text': 'User or system identifier who performed the action',
            },
            'timestamp': {
                'help_text': 'When the action was performed',
            },
            'changes': {
                'help_text': 'JSON object containing before/after values of changed fields',
            },
            'description': {
                'help_text': 'Human-readable description of the change',
            },
        }
